/* Paycheck Calculator — shared 2026 engine bridge */
(function(){
  var initialized=false, requestToken=0;
  var LOCAL_OPTIONS={NY:['NYC'],PA:['PHILADELPHIA'],MI:['DETROIT']};
  var LOCAL_LABELS={NYC:'New York City',PHILADELPHIA:'Philadelphia',DETROIT:'Detroit'};
  function el(id){return document.getElementById(id);}
  function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)||0);}
  function percent(n){return (Number(n)||0).toFixed(1)+'%';}
  function numberValue(id){var node=el(id);if(!node)return 0;var n=parseFloat(String(node.value||'').replace(/[$,\s]/g,''));return Number.isFinite(n)?n:0;}
  function getPeriods(f){return {weekly:52,biweekly:26,semimonthly:24,monthly:12}[f]||26;}
  function setBusy(b){var form=el('pc-form'),ledger=el('pc-ledger'),btn=el('pc-calculate-btn');if(form)form.setAttribute('aria-busy',b?'true':'false');if(ledger)ledger.setAttribute('aria-busy',b?'true':'false');if(btn){btn.disabled=b;btn.textContent=b?'Calculating…':'Calculate';}}
  function ensureStates(states){var select=el('pc-state');if(!select||select.options.length)return;Object.keys(states).sort(function(a,b){return String(states[a].name||a).localeCompare(String(states[b].name||b));}).forEach(function(abbr){var o=document.createElement('option');o.value=abbr;o.textContent=states[abbr].name||abbr;select.appendChild(o);});select.value='TX';}
  function ensureLocalControls(){var state=el('pc-state');if(!state||el('pc-local'))return;var wrap=state.closest('.input-group');if(!wrap)return;var g=document.createElement('div');g.className='input-group';g.innerHTML='<label for="pc-local">Local Tax Location</label><select id="pc-local"><option value="">No supported local tax</option></select><p class="helper-text">Choose a supported city/local income tax when applicable.</p>';var r=document.createElement('div');r.className='input-group';r.innerHTML='<label for="pc-local-residency">Local Residency</label><select id="pc-local-residency"><option value="resident">Resident</option><option value="nonresident">Nonresident</option></select>';wrap.parentNode.insertBefore(g,wrap.nextSibling);wrap.parentNode.insertBefore(r,g.nextSibling);el('pc-local').addEventListener('change',calculate);el('pc-local-residency').addEventListener('change',calculate);refreshLocalOptions();}
  function refreshLocalOptions(){var state=el('pc-state'),select=el('pc-local');if(!state||!select)return;var prev=select.value;select.innerHTML='<option value="">No supported local tax</option>';(LOCAL_OPTIONS[state.value]||[]).forEach(function(code){var o=document.createElement('option');o.value=code;o.textContent=LOCAL_LABELS[code]||code;select.appendChild(o);});select.value=(LOCAL_OPTIONS[state.value]||[]).indexOf(prev)!==-1?prev:'';var residency=el('pc-local-residency');if(residency)residency.disabled=!select.value;}
  function ensureLedgerBody(){var body=document.querySelector('#pc-ledger .ledger__body');if(!body)return;body.innerHTML='<div class="ledger__row"><span class="ledger__label">Gross Pay (per period)</span><span class="ledger__value" id="out-pc-gross">—</span></div><div class="ledger__row"><span class="ledger__label">Pre-tax Deductions (401(k), HSA, health)</span><span class="ledger__value" id="out-pc-deductions-period">—</span></div><div class="ledger__row"><span class="ledger__label">Federal Income Tax (est.)</span><span class="ledger__value" id="out-pc-federal">—</span></div><div class="ledger__row"><span class="ledger__label">State Income Tax (est.)</span><span class="ledger__value" id="out-pc-state">—</span></div><div id="pc-state-payroll-rows"></div><div id="pc-local-row" class="ledger__row"><span class="ledger__label">Local Income Tax (est.)</span><span class="ledger__value" id="out-pc-local-tax">—</span></div><div class="ledger__row"><span class="ledger__label">Social Security</span><span class="ledger__value" id="out-pc-ss">—</span></div><div class="ledger__row"><span class="ledger__label">Medicare</span><span class="ledger__value" id="out-pc-medicare">—</span></div><div class="ledger__row" id="pc-additional-medicare-row" hidden><span class="ledger__label">Additional Medicare</span><span class="ledger__value" id="out-pc-additional-medicare">—</span></div><div class="ledger__row ledger__row--primary"><span class="ledger__label">Net Pay (est.)</span><span class="ledger__value" id="out-pc-net">—</span></div><div class="ledger__row"><span class="ledger__label">Annual Gross</span><span class="ledger__value" id="out-pc-annual-gross">—</span></div><div class="ledger__row"><span class="ledger__label">Pre-tax Deductions (annual)</span><span class="ledger__value" id="out-pc-deductions">—</span></div><div class="ledger__row"><span class="ledger__label">Annual Net (est.)</span><span class="ledger__value" id="out-pc-annual-net">—</span></div><div class="ledger__row"><span class="ledger__label">Effective Tax Rate</span><span class="ledger__value" id="out-pc-effective-rate">—</span></div>';}
  function renderPayrollRows(details,periods){var wrap=el('pc-state-payroll-rows');if(!wrap)return;wrap.innerHTML='';(details||[]).forEach(function(d){var row=document.createElement('div');row.className='ledger__row';row.innerHTML='<span class="ledger__label">'+d.name+'</span><span class="ledger__value">'+money((Number(d.tax)||0)/periods)+'</span>';wrap.appendChild(row);});}
  function render(result){var ledger=el('pc-ledger');if(!ledger)return;ensureLedgerBody();if(result.error){ledger.hidden=false;el('out-pc-net').textContent='Check inputs';el('pc-state-note').textContent=(result.errors||[]).map(function(e){return e.message;}).join(' · ');return;}var t=result.totals,period=el('pc-frequency')?el('pc-frequency').value:'biweekly',periods=getPeriods(period);var gross=t.grossAnnual/periods,pretax=t.pretaxDeductions/periods,federal=Number(result.federal?.withholding?.federalWithholdingAnnual||0)/periods,state=Number(t.totalStateTax||0)/periods,local=Number(t.totalLocal||0)/periods,ss=Number(result.fica?.socialSecurity?.socialSecurityTax||0)/periods,med=Number(result.fica?.medicare?.medicareTax||0)/periods,add=Number(result.fica?.additionalMedicare?.additionalMedicareWithholding||0)/periods;renderPayrollRows(result.state?.payroll?.details,periods);el('out-pc-gross').textContent=money(gross);el('out-pc-deductions-period').textContent='−'+money(pretax);el('out-pc-federal').textContent='−'+money(federal);el('out-pc-state').textContent='−'+money(state);el('out-pc-local-tax').textContent='−'+money(local);el('out-pc-ss').textContent='−'+money(ss);el('out-pc-medicare').textContent='−'+money(med);var addRow=el('pc-additional-medicare-row');if(addRow){addRow.hidden=add<=0;el('out-pc-additional-medicare').textContent='−'+money(add);}var localRow=el('pc-local-row');if(localRow)localRow.hidden=!(result.local&&result.local.selected) && !(result.state&&result.state.localTax&&result.state.localTax.exists);el('out-pc-net').textContent=money(t.netPerSelectedPeriod);el('out-pc-annual-gross').textContent=money(result.grossAnnual);el('out-pc-deductions').textContent=money(t.totalDeductions);el('out-pc-annual-net').textContent=money(t.netAnnual);el('out-pc-effective-rate').textContent=percent(t.effectiveTaxRate);var note=el('pc-state-note');if(note){var parts=['2026 estimate',result.stateName||result.stateAbbr,'Engine v'+result.ENGINE_VERSION];if(result.state?.statusWarning)parts.push(result.state.statusWarning);if(result.local?.note)parts.push(result.local.note);note.textContent=parts.join(' · ');}ledger.hidden=false;window.__lastPaycheckResult=result;}
  async function calculate(){var token=++requestToken;setBusy(true);try{var loaded=await Promise.all([import('./tax-engine/index.js'),import('../data/states-2026.js')]);if(token!==requestToken)return;var engine=loaded[0],states=loaded[1].STATES_2026;ensureStates(states);ensureLocalControls();refreshLocalOptions();var raw={grossAnnual:numberValue('pc-salary'),state:(el('pc-state')?.value)||'TX',filingStatus:(el('pc-filing-status')?.value)||'single',payFrequency:'annual',selectedPayPeriod:(el('pc-frequency')?.value)||'biweekly',age:0,localJurisdiction:(el('pc-local')?.value)||'',localResidency:(el('pc-local-residency')?.value)||'resident',deductions:{traditional401kPercent:numberValue('pc-401k'),hsa:numberValue('pc-hsa'),hsaCoverage:(el('pc-hsa-coverage')?.value)||'self',healthPremiums:numberValue('pc-health-premiums')},w4:{}};if(raw.grossAnnual<=0){var blank=el('pc-ledger');if(blank)blank.hidden=true;return;}render(engine.calculateAll(engine.sanitizeInputs(raw)));}catch(err){if(token!==requestToken)return;console.error('calculate() failed:',err);var l=el('pc-ledger');if(l)l.hidden=false;if(el('out-pc-net'))el('out-pc-net').textContent='Unable to calculate';if(el('pc-state-note'))el('pc-state-note').textContent='We could not calculate this paycheck. Please check your inputs and try again.';}finally{if(token===requestToken)setBusy(false);}}
  function init(){if(initialized)return;var form=el('pc-form');if(!form)return;initialized=true;var ledger=el('pc-ledger');if(ledger){ledger.setAttribute('aria-live','polite');ledger.setAttribute('aria-atomic','true');ledger.setAttribute('aria-busy','false');}['pc-salary','pc-frequency','pc-state','pc-filing-status','pc-401k','pc-hsa','pc-hsa-coverage','pc-health-premiums'].forEach(function(id){var node=el(id);if(node){node.addEventListener('input',calculate);node.addEventListener('change',function(){if(id==='pc-state')refreshLocalOptions();calculate();});}});form.addEventListener('submit',function(e){e.preventDefault();calculate();});var reset=el('pc-reset-btn');if(reset)reset.addEventListener('click',function(){form.reset();if(el('pc-frequency'))el('pc-frequency').value='biweekly';if(el('pc-state'))el('pc-state').value='TX';if(el('pc-filing-status'))el('pc-filing-status').value='single';refreshLocalOptions();if(ledger)ledger.hidden=true;});var copy=el('pc-copy-btn');if(copy)copy.addEventListener('click',function(){var r=window.__lastPaycheckResult;if(!r||!window.copyToClipboard)return;var t=r.totals;window.copyToClipboard(['US Salary Tools — 2026 Paycheck Estimate','Annual Gross: '+money(r.grossAnnual),'Pre-tax Deductions: '+money(t.pretaxDeductions),'Federal Income Tax: '+money(r.federal?.withholding?.federalWithholdingAnnual||0),'State Income Tax: '+money(t.totalStateTax),'State Payroll Taxes: '+money(t.totalStatePayroll),'Local Income Tax: '+money(t.totalLocal),'Social Security: '+money(r.fica?.socialSecurity?.socialSecurityTax||0),'Medicare: '+money(r.fica?.medicare?.medicareTax||0),'Additional Medicare: '+money(r.fica?.additionalMedicare?.additionalMedicareWithholding||0),'Annual Net: '+money(t.netAnnual)].join('\n'));});var print=el('pc-print-btn');if(print)print.addEventListener('click',function(){window.print();});calculate();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
